name: Docker Compose Build

on:
  pull_request:
    paths:
      - 'docker/**'
      - 'conf/**'
      - 'compose.yml'
      - 'lila-docker'
      - 'scripts/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: ./lila-docker build
      - run: docker image ls
